// <auto-generated />
using System;
using System.Collections.Generic;
using CharacterCrucible.CoreApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CharacterCrucible.CoreApi.Persistence.Migrations
{
    [DbContext(typeof(CharacterCrucibleDbContext))]
    partial class CharacterCrucibleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.AbilityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AbilityType")
                        .HasColumnType("integer")
                        .HasColumnName("ability_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_approval");

                    b.Property<Guid>("RulesetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CostRule", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.AbilityDefinition.CostRule#CostRule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Factor")
                                .HasColumnType("integer")
                                .HasColumnName("cost_rule_factor");

                            b1.Property<int>("Op")
                                .HasColumnType("integer")
                                .HasColumnName("cost_rule_op");

                            b1.Property<int>("Operand")
                                .HasColumnType("integer")
                                .HasColumnName("cost_rule_operand");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "PrerequisiteGroups", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.AbilityDefinition.PrerequisiteGroups#PrerequisiteGroup", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("RequiredCount");

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "EntryValues", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.AbilityDefinition.PrerequisiteGroups#PrerequisiteGroup.EntryValues#PrerequisiteEntry", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Kind");

                                    b2.Property<int?>("MinimumRating");

                                    b2.Property<string>("TargetKey")
                                        .IsRequired();
                                });

                            b1
                                .ToJson("prerequisite_groups")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_ability_definition");

                    b.HasIndex("RulesetVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_ability_definition_ruleset_version_id_key");

                    b.ToTable("ability_definition", "rulesets");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.ArchetypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RulesetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Caps", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.ArchetypeDefinition.Caps#CapModifier", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("MaxOverride");

                            b1.Property<string>("TargetKey")
                                .IsRequired();

                            b1
                                .ToJson("caps")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Modifiers", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.ArchetypeDefinition.Modifiers#CostModifier", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Factor");

                            b1.Property<string>("TargetKey")
                                .IsRequired();

                            b1.Property<int>("TargetKind");

                            b1
                                .ToJson("modifiers")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Ranks", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.ArchetypeDefinition.Ranks#GrantedRank", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Ranks");

                            b1.Property<string>("TraitKey")
                                .IsRequired();

                            b1
                                .ToJson("ranks")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_archetype_definition");

                    b.HasIndex("RulesetVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_archetype_definition_ruleset_version_id_key");

                    b.ToTable("archetype_definition", "rulesets");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.DomainDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RulesetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "BandValues", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.DomainDefinition.BandValues#DomainBand", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Label")
                                .IsRequired();

                            b1.Property<int>("MinimumScore");

                            b1
                                .ToJson("band_values")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_domain_definition");

                    b.HasIndex("RulesetVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_domain_definition_ruleset_version_id_key");

                    b.ToTable("domain_definition", "rulesets");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.Ruleset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<Guid?>("DerivedFrom")
                        .HasColumnType("uuid")
                        .HasColumnName("derived_from");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher");

                    b.HasKey("Id")
                        .HasName("pk_ruleset");

                    b.HasIndex("CurrentVersionId")
                        .HasDatabaseName("ix_ruleset_current_version_id");

                    b.ToTable("ruleset", "rulesets");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("major_version");

                    b.Property<int>("MinorVersion")
                        .HasColumnType("integer")
                        .HasColumnName("minor_version");

                    b.Property<string>("ReleaseNotes")
                        .HasColumnType("text")
                        .HasColumnName("release_notes");

                    b.Property<int>("ReleaseType")
                        .HasColumnType("integer")
                        .HasColumnName("release_type");

                    b.Property<Guid>("RulesetId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Publication", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion.Publication#PublicationRecord", b1 =>
                        {
                            b1.Property<string>("ContentHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("publication_content_hash");

                            b1.Property<Guid>("PublishedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("publication_published_by");

                            b1.Property<string>("PublishedContent")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("publication_published_content");

                            b1.Property<DateTimeOffset>("PublishedDate")
                                .HasColumnType("timestamptz")
                                .HasColumnName("publication_published_date");

                            b1.Property<string>("Publisher")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("publication_publisher");

                            b1.Property<string>("RulesetName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("publication_ruleset_name");

                            b1.Property<int>("SchemaVersion")
                                .HasColumnType("integer")
                                .HasColumnName("publication_schema_version");
                        });

                    b.HasKey("Id")
                        .HasName("pk_ruleset_version");

                    b.HasIndex("RulesetId")
                        .IsUnique()
                        .HasDatabaseName("ux_ruleset_version_one_draft_per_ruleset")
                        .HasFilter("publication_schema_version IS NULL");

                    b.HasIndex("RulesetId", "MajorVersion", "MinorVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_ruleset_version_ruleset_id_major_minor");

                    b.ToTable("ruleset_version", "rulesets");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.TraitDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DomainKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain_key");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<int>("MaxValue")
                        .HasColumnType("integer")
                        .HasColumnName("max_value");

                    b.Property<int>("MinValue")
                        .HasColumnType("integer")
                        .HasColumnName("min_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RulesetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruleset_version_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CostRule", "CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.TraitDefinition.CostRule#CostRule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Factor")
                                .HasColumnType("integer")
                                .HasColumnName("cost_rule_factor");

                            b1.Property<int>("Op")
                                .HasColumnType("integer")
                                .HasColumnName("cost_rule_op");

                            b1.Property<int>("Operand")
                                .HasColumnType("integer")
                                .HasColumnName("cost_rule_operand");
                        });

                    b.HasKey("Id")
                        .HasName("pk_trait_definition");

                    b.HasIndex("RulesetVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_trait_definition_ruleset_version_id_key");

                    b.ToTable("trait_definition", "rulesets");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.AbilityDefinition", b =>
                {
                    b.HasOne("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", null)
                        .WithMany("AbilityDefinitions")
                        .HasForeignKey("RulesetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ability_definition_ruleset_versions_ruleset_version_id");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.ArchetypeDefinition", b =>
                {
                    b.HasOne("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", null)
                        .WithMany("ArchetypeDefinitions")
                        .HasForeignKey("RulesetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archetype_definition_ruleset_versions_ruleset_version_id");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.DomainDefinition", b =>
                {
                    b.HasOne("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", null)
                        .WithMany("DomainDefinitions")
                        .HasForeignKey("RulesetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_domain_definition_ruleset_versions_ruleset_version_id");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.Ruleset", b =>
                {
                    b.HasOne("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ruleset_ruleset_versions_current_version_id");

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", b =>
                {
                    b.HasOne("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.Ruleset", null)
                        .WithMany("Versions")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ruleset_version_ruleset_ruleset_id");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.TraitDefinition", b =>
                {
                    b.HasOne("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", null)
                        .WithMany("TraitDefinitions")
                        .HasForeignKey("RulesetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trait_definition_ruleset_versions_ruleset_version_id");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.Ruleset", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CharacterCrucible.CoreApi.Modules.Rulesets.Domain.Entities.RulesetVersion", b =>
                {
                    b.Navigation("AbilityDefinitions");

                    b.Navigation("ArchetypeDefinitions");

                    b.Navigation("DomainDefinitions");

                    b.Navigation("TraitDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
